logging:
 level:
  gov:
   tna:
    discovery:
     taxonomy: DEBUG


spring:
 data:
  mongodb:
   host: ***REMOVED***.***REMOVED***
   port: 27017
   database: taxonomy

  mongo:
   repositories:
    enabled: true

async:
 executor:
  corePoolSize: 7
  maxPoolSize: 42
  queueCapacity: 11

lucene:
 mlt:
  mimimumScoreForMlt: 0.001
  mimimumGlobalScoreForACategory: 0
  maximumSimilarElements: 500
  minTermFreq: 1
  minDocFreq: 1
  
 index:
  iaviewCollectionPath: ***REMOVED***solr/collection4/data/index
  trainingSetCollectionPath: ***REMOVED***solr/collection2/data/index
  version: LUCENE_47
  maxTrainingDocsPerCategory: 5000
  maxShingleSize: 3