logging:
 config: classpath:log4j-tooling.properties
 level:
  gov:
   tna:
    discovery:
     taxonomy: INFO




spring:
 data:
  mongodb:
   host: ***REMOVED***.***REMOVED***
   port: 27017
   database: taxonomy

  mongo:
   repositories:
    enabled: true

async:
 executor:
  corePoolSize: 7
  maxPoolSize: 42
  queueCapacity: 11

lucene:
 mlt:
  mimimumScoreForMlt: 0
  mimimumGlobalScoreForACategory: 0
  maximumSimilarElements: 2000
  minTermFreq: 1
  minDocFreq: 2
  
 index:
  iaviewCollectionPath: ***REMOVED***solr/collection4/data/index
  trainingSetCollectionPath: ***REMOVED***solr/collection2/data/index
  version: LUCENE_47
  maxTrainingDocsPerCategory: 5000
  maxShingleSize: 0
  useStopFilter: false
  useSynonymFilter: false