spring.profiles.active: queryBased,local

logging.level.uk.gov.nationalarchives.discovery.taxonomy: DEBUG

spring:
 data:
  mongodb:
   host: localhost
   port: 27017
   database: taxonomy

  mongo:
   repositories:
    enabled: true

mongo.categories:
 port: 27017
 database: taxonomy

async:
 fsSearch:
  threadPoolSize: 3
  queueCapacity: 200
 memorySearch:
  threadPoolSize: 5
  queueCapacity: 200

lucene:
 mlt:
  fieldsToAnalyse: DESCRIPTION,TITLE,CONTEXTDESCRIPTION,CORPBODYS,SUBJECTS,PERSON_FULLNAME,PLACE_NAME,CATDOCREF
  mimimumScoreForMlt: 0
  mimimumGlobalScoreForACategory: 0
  maximumSimilarElements: 2000
  minTermFreq: 1
  minDocFreq: 2
  titleBoostingFactor: 0.25
  descBoostingFactor: 2
  contextDescBoostingFactor: 0.75

 index:
  version: LUCENE_4_10_3
  maxTrainingDocsPerCategory: 5000
  maxShingleSize: 0
  useStopFilter: false
  useSynonymFilter: true
  queryFilterSourceValues: 100,200
  iaViewMaxMergeSizeMB: 5.0
  iaViewMaxCachedMB: 60.0
  defaultTaxonomyField: textnocasnopunc

---
spring.profiles: queryBased
lucene:
 categoriser:
  useTSetBasedCategoriser: false
  useQueryBasedCategoriser: true
  
---
spring.profiles: tsetBased
lucene:
 categoriser:
  useTSetBasedCategoriser: true
  useQueryBasedCategoriser: false

---
spring.profiles: local

mongo.categories.host: localhost

lucene.index:
 iaviewCollectionPath: /mnt/search_indexes/index_20150217/data/index
 trainingSetCollectionPath: /opt/solr/solr/collection2/data/index
  
logging.config: classpath:log4j.properties

---
spring.profiles: tooling

mongo.categories.host: ***REMOVED***.***REMOVED***
   
lucene.index:
 iaviewCollectionPath: ***REMOVED***solr/collection5/data/index
 trainingSetCollectionPath: ***REMOVED***solr/collection2/data/index

logging.config: classpath:log4j-tooling.properties

---
spring.profiles: test-platform

mongo.categories.host: ***REMOVED***.***REMOVED***
   
lucene.index:
 iaviewCollectionPath: ***REMOVED***solr/collection1/data/index
 trainingSetCollectionPath: ***REMOVED***solr/collection2/data/index

logging.config: "classpath:log4j-test.properties"
logging.level.uk.gov.nationalarchives.discovery.taxonomy: INFO

spring.activemq:
 broker-url: tcp://localhost:8984
 user***REMOVED***
 password***REMOVED***
  