spring.profiles.active: queryBased,local

logging:
 level:
  gov:
   tna:
    discovery:
     taxonomy: DEBUG

spring:
 data:
  mongodb:
   port: 27017
   database: taxonomy

  mongo:
   repositories:
    enabled: true

async:
 executor:
  corePoolSize: 3
  maxPoolSize: 3
  queueCapacity: 150

lucene:
 loadTSetServiceLayer: true
 categoriser:
  fieldsToAnalyse: DESCRIPTION,TITLE,CONTEXTDESCRIPTION,CORPBODYS,SUBJECTS,PERSON_FULLNAME,PLACE_NAME,CATDOCREF
 mlt:
  mimimumScoreForMlt: 0
  mimimumGlobalScoreForACategory: 0
  maximumSimilarElements: 2000
  minTermFreq: 1
  minDocFreq: 2
  titleBoostingFactor: 0.25
  descBoostingFactor: 2
  contextDescBoostingFactor: 0.75

 index:
  version: LUCENE_4_10_3
  maxTrainingDocsPerCategory: 5000
  maxShingleSize: 0
  useStopFilter: false
  useSynonymFilter: true
  queryFilterSourceValue: 100
  fieldsToSearch: texttax,CATDOCREF
  iaViewMaxMergeSizeMB: 5.0
  iaViewMaxCachedMB: 60.0
  defaultTaxonomyField: textnocasnopunc
  
---
spring.profiles: local

spring.data.mongodb:
 host: localhost

lucene.index:
 iaviewCollectionPath: /mnt/search_indexes/index_20150217/data/index
 trainingSetCollectionPath: /opt/solr/solr/collection2/data/index
  
logging.config: classpath:log4j.properties

---
spring.profiles: tooling

spring.data.mongodb:
 host: ***REMOVED***.***REMOVED***
   
lucene.index:
 iaviewCollectionPath: ***REMOVED***solr/collection4/data/index
 trainingSetCollectionPath: ***REMOVED***solr/collection2/data/index

logging.config: classpath:log4j-tooling.properties
  
---
spring.profiles: queryBased
lucene:
 categoriser:
  useTSetBasedCategoriser: false
  useQueryBasedCategoriser: true
  
---
spring.profiles: tsetBased
lucene:
 categoriser:
  useTSetBasedCategoriser: true
  useQueryBasedCategoriser: false