logging:
 config: classpath:log4j.properties
 level:
  gov:
   tna:
    discovery:
     taxonomy: DEBUG

server:
 port: 8090

spring:
 data:
  mongodb:
   host: localhost
   port: 27017
   database: taxonomy

  mongo:
   repositories:
    enabled: true

async:
 executor:
  corePoolSize: 7
  maxPoolSize: 42
  queueCapacity: 11

lucene:
 categoriser:
  useTSetBasedCategoriser: true
  useQueryBasedCategoriser: false
 mlt:
  mimimumScoreForMlt: 0
  mimimumGlobalScoreForACategory: 0
  maximumSimilarElements: 2000
  minTermFreq: 1
  minDocFreq: 2
  titleBoostingFactor: 2
  descBoostingFactor: 2
  contextDescBoostingFactor: 0.5

 index:
  iaviewCollectionPath: /opt/solr/solr/collection1/data/index
  trainingSetCollectionPath: /opt/solr/solr/collection2/data/index
  version: LUCENE_47
  maxTrainingDocsPerCategory: 5000
  maxShingleSize: 0
  useStopFilter: false
  useSynonymFilter: false