spring.profiles.active: queryBased,local,batch

logging:
 level:
  gov:
   tna:
    discovery:
     taxonomy: DEBUG

spring:
 data:
  mongodb:
   host: localhost
   port: 27017
   database: taxonomy

  mongo:
   repositories:
    enabled: true

mongo.categories:
 port: 27017
 database: taxonomy

async:
 executor:
  corePoolSize: 3
  maxPoolSize: 3
  queueCapacity: 150

lucene:
 mlt:
  fieldsToAnalyse: DESCRIPTION,TITLE,CONTEXTDESCRIPTION,CORPBODYS,SUBJECTS,PERSON_FULLNAME,PLACE_NAME,CATDOCREF
  mimimumScoreForMlt: 0
  mimimumGlobalScoreForACategory: 0
  maximumSimilarElements: 2000
  minTermFreq: 1
  minDocFreq: 2
  titleBoostingFactor: 0.25
  descBoostingFactor: 2
  contextDescBoostingFactor: 0.75

 index:
  version: LUCENE_4_10_3
  maxTrainingDocsPerCategory: 5000
  maxShingleSize: 0
  useStopFilter: false
  useSynonymFilter: true
  queryFilterSourceValue: 100
  iaViewMaxMergeSizeMB: 5.0
  iaViewMaxCachedMB: 60.0
  defaultTaxonomyField: textnocasnopunc

---
spring.profiles: queryBased
lucene:
 categoriser:
  useTSetBasedCategoriser: false
  useQueryBasedCategoriser: true
  
---
spring.profiles: tsetBased
lucene:
 categoriser:
  useTSetBasedCategoriser: true
  useQueryBasedCategoriser: false

---
spring.profiles: batch
spring.activemq.categorise-doc-queue-name: CATEGORISE.DOCUMENTS

---
spring.profiles: local

mongo.categories.host: localhost

lucene.index:
 iaviewCollectionPath: /mnt/search_indexes/index_20150217/data/index
 trainingSetCollectionPath: /opt/solr/solr/collection2/data/index
  
logging.config: classpath:log4j.properties

spring.activemq:
 broker-url: tcp://localhost:61616
 user***REMOVED***
 password***REMOVED***
 
solr.host: http://localhost:8983/solr/IAView_subset/
---
spring.profiles: tooling

mongo.categories.host: ***REMOVED***.***REMOVED***
   
lucene.index:
 iaviewCollectionPath: ***REMOVED***solr/collection5/data/index
 trainingSetCollectionPath: ***REMOVED***solr/collection2/data/index

logging.config: classpath:log4j-tooling.properties

spring.activemq:
 broker-url: tcp://localhost:61616
 user***REMOVED***
 password***REMOVED***
 
solr.host: http://localhost:8983/solr/IAView_subset/  

